apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitter
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: crb-gitter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: gitter
  namespace: ${workshopNamespace}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitter
spec:
  rules:
  - host: session.${domain}
    http:
      paths:
      - backend:
          serviceName: gitter
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitter
  name: gitter
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gitter
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: gitter
  name: gitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitter
  strategy: {}
  template:
    metadata:
      labels:
        app: gitter
    spec:
      serviceAccountName: gitter 
      containers:
      - image: lalyos/gitter-scripter
        name: gitter
        env:
          - name: DOMAIN
            value: session.${domain}
        envFrom:
          - secretRef:
              name: gitter
        ports:
        - containerPort: 8080
        resources: {}
